import { useCallback, useEffect, useRef, useState } from "react";
import { profile } from "../content/profile";
import { repos } from "../content/github";
import type { FocusId } from "./DeskModel";

// Tracks live in public/audio/. Add/remove here; empty ⇒ the iPod panel shows no
// player and the mute toggle is hidden. All AI-generated by Carlos, so the artist
// is profile.name (rendered in the player) — no per-track artist needed.
const TRACKS: { title: string; src: string }[] = [
  { title: "Midnight Rhodes Drift", src: "/audio/midnight-rhodes-drift.mp3" },
  { title: "Tea House Cadence", src: "/audio/tea-house-cadence.mp3" },
  { title: "Maple Window Groove", src: "/audio/maple-window-groove.mp3" },
  { title: "Paper Lantern Swing", src: "/audio/paper-lantern-swing.mp3" },
  { title: "Midnight Swing", src: "/audio/midnight-swing.mp3" },
  { title: "Japanese Jazzhop Lo-Fi", src: "/audio/japanese-jazzhop-lo-fi.mp3" },
];

const LABEL: Record<FocusId, string> = {
  monitor: "the monitor",
  ipod: "the iPod",
  phone: "the phone",
  clipboard: "the clipboard",
  floppy: "the floppy disk",
};

// Random track index, never the one currently playing (no repeat back-to-back).
function randomTrack(exclude: number | null): number {
  if (TRACKS.length <= 1) return 0;
  let n = Math.floor(Math.random() * TRACKS.length);
  while (n === exclude) n = Math.floor(Math.random() * TRACKS.length);
  return n;
}

type Music = {
  ref: React.RefObject<HTMLAudioElement | null>;
  track: (typeof TRACKS)[number] | null;
  history: number[]; // track indices in the order they started playing
  playing: boolean;
  muted: boolean;
  next: () => void;
  toggle: () => void;
  toggleMute: () => void;
};

// Playback state hoisted here (Overlays is always mounted) so music keeps playing
// after the iPod close-up is dismissed. Opening the iPod the first time starts a
// random track; it shuffles (no immediate repeats) on end/next and never restarts
// on reopen.
function useMusic(focus: FocusId | null): Music {
  const ref = useRef<HTMLAudioElement>(null);
  const [idx, setIdx] = useState<number | null>(null);
  const [history, setHistory] = useState<number[]>([]);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(false);

  useEffect(() => {
    if (focus === "ipod" && idx === null && TRACKS.length > 0) setIdx(randomTrack(null));
  }, [focus, idx]);

  // Play whenever the track changes (the first play rides the iPod-click gesture),
  // and record it in the play history.
  useEffect(() => {
    const a = ref.current;
    if (!a || idx === null) return;
    setHistory((h) => (h[h.length - 1] === idx ? h : [...h, idx]));
    a.play().then(() => setPlaying(true)).catch(() => setPlaying(false));
  }, [idx]);

  useEffect(() => {
    if (ref.current) ref.current.muted = muted;
  }, [muted]);

  const next = useCallback(() => setIdx((i) => randomTrack(i)), []);
  const toggle = useCallback(() => {
    const a = ref.current;
    if (!a) return;
    if (a.paused) {
      a.play();
      setPlaying(true);
    } else {
      a.pause();
      setPlaying(false);
    }
  }, []);
  const toggleMute = useCallback(() => setMuted((m) => !m), []);

  return { ref, track: idx === null ? null : TRACKS[idx], history, playing, muted, next, toggle, toggleMute };
}

export function Overlays({
  focus,
  hover,
  onClose,
}: {
  focus: FocusId | null;
  hover: FocusId | null;
  onClose: () => void;
}) {
  const music = useMusic(focus);

  return (
    <div className="pointer-events-none fixed inset-0 z-10">
      {/* Persistent audio: outlives the iPod panel, so music keeps playing once
          the close-up is dismissed. */}
      {TRACKS.length > 0 && (
        <audio ref={music.ref} src={music.track?.src} onEnded={music.next} />
      )}

      {/* Always-available mute toggle. */}
      {TRACKS.length > 0 && (
        <button
          onClick={music.toggleMute}
          aria-label={music.muted ? "Unmute music" : "Mute music"}
          className="pointer-events-auto absolute bottom-6 left-6 flex items-center gap-2 rounded-full bg-black/55 px-4 py-2 font-mono text-sm text-white/85 backdrop-blur-sm transition hover:bg-black/70"
        >
          <span aria-hidden>{music.muted ? "🔇" : "🔊"}</span>
          <span className="hidden sm:inline">{music.muted ? "Muted" : "Music"}</span>
        </button>
      )}

      {/* hover affordance in the hero view */}
      {!focus && hover && (
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 rounded-full bg-black/60 px-4 py-2 font-mono text-sm text-white/90 backdrop-blur-sm">
          Click {LABEL[hover]} →
        </div>
      )}

      {/* The monitor's content lives on the screen itself (MonitorScreen), not
          in a side panel. */}
      {focus === "ipod" && (
        <Panel title="Now playing" onClose={onClose}>
          <IpodBody music={music} />
        </Panel>
      )}
      {focus === "phone" && (
        <Panel title="Contact" onClose={onClose}>
          <PhoneBody />
        </Panel>
      )}
      {focus === "floppy" && (
        <Panel title="GitHub projects" onClose={onClose}>
          <FloppyBody />
        </Panel>
      )}
      {focus === "clipboard" && (
        <Panel title="Résumé" onClose={onClose}>
          <ClipboardBody />
        </Panel>
      )}
    </div>
  );
}

function Panel({
  title,
  onClose,
  children,
}: {
  title: string;
  onClose: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="panel-in pointer-events-auto absolute inset-y-0 right-0 flex w-full max-w-md flex-col bg-[#111318]/92 text-white shadow-2xl backdrop-blur-md sm:max-w-lg">
      <header className="flex items-center justify-between border-b border-white/10 px-6 py-4">
        <h2 className="font-display text-lg tracking-tight text-white">{title}</h2>
        <button
          onClick={onClose}
          aria-label="Close (Esc)"
          className="rounded-md px-2 py-1 font-mono text-sm text-white/60 transition hover:bg-white/10 hover:text-white"
        >
          Esc ✕
        </button>
      </header>
      <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">{children}</div>
    </div>
  );
}

function IpodBody({ music }: { music: Music }) {
  // Recently played = the history minus the current track, most-recent first, last 5.
  const recent = music.history.slice(0, -1).slice(-5).reverse();
  return (
    <div className="space-y-6">
      <NowPlaying music={music} />

      <section className="space-y-3">
        <h3 className="font-mono text-[10px] uppercase tracking-widest text-white/40">
          Recently played
        </h3>
        {recent.length === 0 ? (
          <p className="font-mono text-xs text-white/40">Nothing yet — hit next ⏭</p>
        ) : (
          <ol className="space-y-2 font-mono text-sm">
            {recent.map((i, n) => (
              <li key={`${i}-${n}`} className="flex gap-3 text-white/70">
                <span className="text-white/30">{n + 1}</span>
                <span className="truncate">{TRACKS[i].title}</span>
              </li>
            ))}
          </ol>
        )}
      </section>
    </div>
  );
}

function PhoneBody() {
  return (
    <div className="space-y-4">
      <p className="font-mono text-sm leading-relaxed text-white/70">{profile.lede}</p>
      <ul className="space-y-2 font-mono text-sm">
        <li>
          <a className="text-white/80 underline-offset-4 hover:underline" href={`mailto:${profile.email}`}>
            {profile.email}
          </a>
        </li>
        <li>
          <a className="text-white/80 underline-offset-4 hover:underline" href={profile.github} target="_blank" rel="noreferrer">
            github.com/{profile.githubHandle}
          </a>
        </li>
        <li>
          <a className="text-white/80 underline-offset-4 hover:underline" href={profile.linkedin} target="_blank" rel="noreferrer">
            LinkedIn
          </a>
        </li>
        <li className="text-white/50">{profile.location}</li>
      </ul>
    </div>
  );
}

function FloppyBody() {
  return (
    <div className="space-y-4">
      {repos.map((r) => (
        <div key={r.name} className="rounded-xl border border-white/10 bg-white/[0.04] p-4">
          <div className="flex items-start justify-between gap-3">
            <h3 className="font-display text-base">{r.name}</h3>
            {r.repo && (
              <a
                href={r.repo}
                target="_blank"
                rel="noreferrer"
                className="shrink-0 font-mono text-xs text-white/50 hover:text-white/80"
              >
                Source ↗
              </a>
            )}
          </div>
          <p className="mt-1 font-mono text-xs leading-relaxed text-white/60">{r.blurb}</p>
          <div className="mt-3 flex flex-wrap gap-1.5">
            {r.tags.map((t) => (
              <span key={t} className="rounded-full bg-white/10 px-2 py-0.5 font-mono text-[10px] text-white/60">
                {t}
              </span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function ClipboardBody() {
  return (
    <div className="flex h-full flex-col gap-4">
      <p className="font-mono text-sm leading-relaxed text-white/70">{profile.lede}</p>
      <iframe
        src={profile.resume}
        title="Résumé"
        className="min-h-64 w-full flex-1 rounded-lg border border-white/10 bg-white/5"
      />
      <a
        href={profile.resume}
        target="_blank"
        rel="noreferrer"
        className="self-start rounded-full bg-white px-4 py-1.5 font-mono text-xs font-bold text-black transition hover:bg-white/85"
      >
        Open / download PDF ↗
      </a>
    </div>
  );
}

function NowPlaying({ music }: { music: Music }) {
  if (TRACKS.length === 0) {
    return (
      <p className="rounded-lg border border-dashed border-white/15 p-3 font-mono text-xs text-white/40">
        ♪ tracks coming soon
      </p>
    );
  }
  return (
    <div className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/[0.04] p-4">
      <button
        onClick={music.toggle}
        aria-label={music.playing ? "Pause" : "Play"}
        className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-white text-black"
      >
        {music.playing ? "❚❚" : "►"}
      </button>
      <div className="min-w-0 flex-1">
        <p className="truncate font-display text-sm">{music.track?.title ?? "…"}</p>
        <p className="truncate font-mono text-xs text-white/50">{profile.name}</p>
      </div>
      <button
        onClick={music.next}
        aria-label="Next track"
        className="shrink-0 font-mono text-xs text-white/50 hover:text-white/80"
      >
        next ⏭
      </button>
    </div>
  );
}
