import { useCallback, useEffect, useRef, useState } from "react";
import type { FocusId } from "./DeskModel";

// Tracks live in public/audio/ (mp3 + matching .jpg cover pulled from Suno).
// Add/remove here; empty ⇒ the iPod panel shows no player and the mute toggle is
// hidden. All Suno-generated by Carlos, so the artist is profile.name (rendered in
// the player); `suno` links the source track for listening/downloading/remixing.
export const TRACKS: { title: string; src: string; art: string; suno: string }[] = [
  { title: "Midnight Rhodes Drift", src: "/audio/midnight-rhodes-drift.mp3", art: "/audio/midnight-rhodes-drift.jpg", suno: "https://suno.com/s/sJg2Um6JXkWejplK" },
  { title: "Tea House Cadence", src: "/audio/tea-house-cadence.mp3", art: "/audio/tea-house-cadence.jpg", suno: "https://suno.com/s/kTQN23dnrWuIcgOy" },
  { title: "Maple Window Groove", src: "/audio/maple-window-groove.mp3", art: "/audio/maple-window-groove.jpg", suno: "https://suno.com/s/RHWwd0Sl6iCKEKmX" },
  { title: "Paper Lantern Swing", src: "/audio/paper-lantern-swing.mp3", art: "/audio/paper-lantern-swing.jpg", suno: "https://suno.com/s/5GEvYAlKkd4Mf34Z" },
  { title: "Midnight Swing", src: "/audio/midnight-swing.mp3", art: "/audio/midnight-swing.jpg", suno: "https://suno.com/s/GPtFQJ3cQ1t6Hj3e" },
  { title: "Japanese Jazzhop Lo-Fi", src: "/audio/japanese-jazzhop-lo-fi.mp3", art: "/audio/japanese-jazzhop-lo-fi.jpg", suno: "https://suno.com/s/bcwrSwA90A2URGCb" },
];

// Random track index, never the one currently playing (no repeat back-to-back).
function randomTrack(exclude: number | null): number {
  if (TRACKS.length <= 1) return 0;
  let n = Math.floor(Math.random() * TRACKS.length);
  while (n === exclude) n = Math.floor(Math.random() * TRACKS.length);
  return n;
}

export type Music = {
  ref: React.RefObject<HTMLAudioElement | null>;
  track: (typeof TRACKS)[number] | null;
  history: number[]; // track indices in the order they started playing
  playing: boolean;
  muted: boolean;
  start: () => void;
  next: () => void;
  toggle: () => void;
  toggleMute: () => void;
};

// Playback state hoisted to DeskCanvas (which renders both the Curtain and the
// always-mounted Overlays) so music survives the iPod close-up AND the curtain's
// Enter click can start it on the same user gesture that unlocks browser audio.
// A track starts on the first iPod focus OR an explicit start(); it shuffles (no
// immediate repeats) on end/next and never restarts on reopen.
export function useMusic(focus: FocusId | null): Music {
  const ref = useRef<HTMLAudioElement>(null);
  const [idx, setIdx] = useState<number | null>(null);
  const [history, setHistory] = useState<number[]>([]);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(false);

  useEffect(() => {
    if (focus === "ipod" && idx === null && TRACKS.length > 0) setIdx(randomTrack(null));
  }, [focus, idx]);

  // Play whenever the track changes (the first play rides a user gesture — iPod
  // click or curtain Enter), and record it in the play history.
  useEffect(() => {
    const a = ref.current;
    if (!a || idx === null) return;
    setHistory((h) => (h[h.length - 1] === idx ? h : [...h, idx]));
    a.play().then(() => setPlaying(true)).catch(() => setPlaying(false));
  }, [idx]);

  useEffect(() => {
    if (ref.current) ref.current.muted = muted;
  }, [muted]);

  // start() plays a random track immediately if nothing's playing yet (idempotent
  // with the iPod auto-start — the idx===null guard prevents a double-start).
  const start = useCallback(() => {
    setIdx((i) => (i === null && TRACKS.length > 0 ? randomTrack(null) : i));
  }, []);
  const next = useCallback(() => setIdx((i) => randomTrack(i)), []);
  const toggle = useCallback(() => {
    const a = ref.current;
    if (!a) return;
    if (a.paused) {
      a.play();
      setPlaying(true);
    } else {
      a.pause();
      setPlaying(false);
    }
  }, []);
  const toggleMute = useCallback(() => setMuted((m) => !m), []);

  return { ref, track: idx === null ? null : TRACKS[idx], history, playing, muted, start, next, toggle, toggleMute };
}
